name: Build and Push Docker Images

on:
  push:
    branches:
      - docker

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push hello-service
        run: |
          docker build ./ -f ./Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to QA Instances
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.QA_IP_1 }},${{ secrets.QA_IP_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
            sudo docker run -d --name hello-service -p 8081:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest

  validate-qa:
    name: Validate QA
    runs-on: ubuntu-latest
    needs: deploy-qa

    steps:
      - name: Test QA Deployment
        run: |
          curl -f http://${{ secrets.QA_IP_1 }}:8081/health || exit 1
          curl -f http://${{ secrets.QA_IP_2 }}:8081/health || exit 1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: validate-qa

    steps:
      - name: Deploy to Production Instances
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PROD_IP_1 }},${{ secrets.PROD_IP_2 }},${{ secrets.PROD_IP_3 }},${{ secrets.PROD_IP_4 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
            sudo docker run -d --name hello-service -p 8081:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
