name: Build and Push Docker Images

on:
  push:
    branches:
      - docker

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push hello-service
        run: |
          docker build ./ -f ./Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to QA Instances
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.QA_IP_1 }},${{ secrets.QA_IP_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Detener y eliminar contenedores existentes
            sudo docker stop hello-service || true
            sudo docker rm hello-service || true
            
            # Descargar la última imagen y desplegar
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service:latest
            sudo docker run -d --name hello-service -p 8081:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/hello-service


            